# Generated by Django 6.0.4 on 2026-05-22 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_administrador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(max_length=100)),
                ('data_disponivel', models.DateField()),
                ('horario_disponivel', models.TimeField()),
                ('porte_local', models.CharField(max_length=20)),
                ('status', models.CharField(default='Recebida', max_length=30)),
                ('detalhes', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=150, null=True)),
                ('cidade', models.CharField(max_length=100)),
                ('solicitacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.solicitacao')),
            ],
        ),
    ]
