# Generated by Django 6.0.4 on 2026-05-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_solicitacao_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='concluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
