# Generated by Django 6.0.4 on 2026-05-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_solicitacao_concluido_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('Recebida', 'Recebida'), ('Em análise', 'Em análise'), ('Agendada', 'Agendada'), ('Em andamento', 'Em andamento'), ('Concluída', 'Concluída'), ('Cancelada', 'Cancelada')], default='Recebida', max_length=30),
        ),
    ]
